language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jpepper8387/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jpepper8387/docker-react npm run test
